MECHANISM_PROFILES = {
    "180_degree_flip_mechanism": {"title": "180 degree flip mechanism"},
    "adjustable_height_table_2": {"title": "Table of adjustable height 2"},
    "circular_iris_shutter_2": {"title": "Circular window Iris shutter 2"},
    "deployable_drone": {"title": "Deployable drone"},
    "hinge_2_dof": {"title": "Hinge of 2 DoF"},
    "kinetic_pyramid_facade": {"title": "Kinetic pyramid facade"},
    "knuckle_joint_press": {"title": "Knuckle joint press"},
    "meat_hash_machine": {"title": "Meat hash machine"},
    "object_8_shaped_runway": {"title": "Object moving along 8-shaped runway"},
    "planetary_gearless_mechanism_2": {"title": "Planetary gearless mechanism 2"},
    "rc_plane_retractable_landing_gear": {"title": "RC plane retractable landing gear"},
    "screw_3_stage_telescopic_actuator_2b": {"title": "Screw 3-stage telescopic actuator 2b"},
    "spatial_planetary_belt_drive": {"title": "Spatial planetary belt drive"},
    "static_balancing_gears_spring": {"title": "Static balancing mechanism using gears and spring"},
    "two_cam_draw_rectangles": {"title": "Two cam mechanism for drawing rectangles"},
    "two_input_shaft_differential_bevel_gearbox": {"title": "Two input shaft differential bevel gearbox"},
    "two_stage_gear_multiplier": {"title": "Two stage gear multiplier"},
    "two_way_linear_to_one_way_rotation_9b": {"title": "Converting two way linear motion into one way rotation 9b"},
    "typewriter_desk": {"title": "Typewriter desk"},
    "wall_mounted_car_shed": {"title": "Wall mounted car shed"},
}
